version: "3.8"

services:
  app:
    container_name: taskcollabapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy # await the health of the service
    ports:
      - "8000:8000"
    volumes:
      - "./taskcollabapi:/usr/app/taskcollabapi:ro"
      - "./prisma:/usr/app/prisma:ro"

  db:
    image: "postgres:17"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 2s
      retries: 5
    ports:
      - "${EXIT_PORT}:${ENTRY_PORT}"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"

  redis:
    image: redis:latest
    container_name: db_redis
    ports:
      - "6379:6379" 
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  postgres_data:
