version: "3.8"

services:
  app:
    container_name: task_collab_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    depends_on:
      db:
        condition: service_healthy # await the health of the service
    ports:
      - "8000:8000"
    volumes:
      - "./task_collab_api:/usr/app/task_collab_api:ro"
      - "./prisma:/usr/app/prisma:ro"

  db:
    image: "postgres:17"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    ports:
      - "${EXIT_PORT}:${ENTRY_PORT}"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"

volumes:
  postgres_data:
